Fix keadm Setup and Initial kubeEdge doc.
kubeedge/website pull request #160
Opened 2021-08-09 07:13 UTC by j13tw

Signed-off-by: ZhengSheng <j13tw@yahoo.com.tw>

* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
1. Add the keadm command for kubeEdge version Setup
2. Add Check edgecore running status
3. Add ```edgecore.service``` not found ```edgecore``` binary
4. Add the Edge Node reset and  Full Clean Command

2021-08-09 13:32 UTC, fisherxu reviewed
Thanks for the fixing, just some nits.

2021-08-09 13:32 UTC, fisherxu commented on content/en/docs/setup/keadm.md
> +1. `--kubeedge-version` is setup the keadm download kubeEdge version, if you not setup it will download newest, kubeEdge release version can refer to [this](https://github.com/kubeedge/kubeedge/relea
```suggestion
1. `--kubeedge-version` is the KubeEdge release version that keadm will install, the default value is the latest release, which you can refer to [releases](https://github.com/kubeedge/kubeedge/releases). 
```

2021-08-09 13:32 UTC, fisherxu commented on content/en/docs/setup/keadm.md
> +# keadm init --advertise-address="THE-EXPOSED-IP"(only work since 1.3 release) --kubeedge-version=1.7.1
```suggestion
# keadm init --advertise-address="THE-EXPOSED-IP" --kubeedge-version="THE-KUBEEDGE-VERSION"
```

2021-08-09 13:32 UTC, fisherxu commented on content/en/docs/setup/keadm.md
> +Watch cloudcore Log
```suggestion
View cloudcore log
```

2021-08-09 13:32 UTC, fisherxu commented on content/en/docs/setup/keadm.md
> +# keadm join --cloudcore-ipport=192.168.20.50:10000 --token=27a37ef16159f7d3be8fae95d588b79b3adaaf92727b72659eb89758c66ffda2.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1OTAyMTYwNzd9.JBj8LLYWXwbb
```suggestion
# keadm join --cloudcore-ipport=192.168.20.50:10000 --token="YOUR_TOKEN" --kubeedge-version="YOUR-KUBEEDGE-VERSION"
```

2021-08-09 13:32 UTC, fisherxu commented on content/en/docs/setup/keadm.md
> +1. The kubeEdge version used in cloud and edge side should be same, and you can uses the `--kubeedge-version` to setup the kubeEdge in specify version.
```suggestion
1. The kubeEdge version used in cloud and edge side should be same, and you can use `--kubeedge-version` to install a specific version of KubeEdge.
```

2021-08-09 13:32 UTC, fisherxu commented on content/en/docs/setup/keadm.md
> +    ```
This part should move to the FAQ doc, we can add a new file/content for it.

2021-08-09 13:32 UTC, fisherxu commented on content/en/docs/setup/keadm.md
> +  ```
Also should move to the FAQ part.

2021-08-10 15:00 UTC, anvithks requested changes
Please check the FAQ page. The points need to be formulated as questions.

2021-10-17 12:15 UTC, closed without merging