add docs about building from source
kubeedge/website pull request #231
Opened 2022-04-18 01:59 UTC by gy95

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
add docs about building from source

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2022-04-19 14:15 UTC, kevin-wangzefeng commented on content/en/docs/setup/local.md
> +You have a working Go environment.
```suggestion
You have a working Go environment, and would like to build on host directly.
```

2022-04-19 14:16 UTC, kevin-wangzefeng commented on content/en/docs/setup/local.md
> +You have a working Docker environment.
```suggestion
You have a working Docker environment. And enjoin building inside container for simpilified environment consistency.
```

2022-04-20 07:45 UTC, Arhell reviewed
/lgtm

2022-04-20 09:51 UTC, anvithks requested changes
Please fix typo. @kevin-wangzefeng please check for the correctness of the commands

2022-04-20 09:51 UTC, anvithks commented on content/en/docs/setup/local.md
> +You have a working Docker environment, and enjoy building inside container for simpilified environment consistency.
Typo: simpilified -> simplified

2022-09-09 00:53 UTC, closed without merging